// Generated by: main
// TypeWriter: slice
// Directive: +gen on Book

package libgogen

// BookSlice is a slice of type Book. Use it where you would use []Book.
type BookSlice []Book

// Where returns a new BookSlice whose elements return true for func. See: http://clipperhouse.github.io/gen/#Where
func (rcv BookSlice) Where(fn func(Book) bool) (result BookSlice) {
	for _, v := range rcv {
		if fn(v) {
			result = append(result, v)
		}
	}
	return result
}
