// Generated by: main
// TypeWriter: slice
// Directive: +gen on Monster

package libgogen

// MonsterSlice is a slice of type Monster. Use it where you would use []Monster.
type MonsterSlice []Monster

// Count gives the number elements of MonsterSlice that return true for the passed func. See: http://clipperhouse.github.io/gen/#Count
func (rcv MonsterSlice) Count(fn func(Monster) bool) (result int) {
	for _, v := range rcv {
		if fn(v) {
			result++
		}
	}
	return
}
