// Generated by: main
// TypeWriter: slice
// Directive: +gen on Movie1

package libgogen

import "errors"

// Movie1Slice is a slice of type Movie1. Use it where you would use []Movie1.
type Movie1Slice []Movie1

// MaxDollars selects the largest value of Dollars in Movie1Slice. Returns error on Movie1Slice with no elements. See: http://clipperhouse.github.io/gen/#MaxCustom
func (rcv Movie1Slice) MaxDollars(fn func(Movie1) Dollars) (result Dollars, err error) {
	l := len(rcv)
	if l == 0 {
		err = errors.New("cannot determine Max of zero-length Movie1Slice")
		return
	}
	result = fn(rcv[0])
	if l > 1 {
		for _, v := range rcv[1:] {
			f := fn(v)
			if f > result {
				result = f
			}
		}
	}
	return
}

// MinDollars selects the least value of Dollars in Movie1Slice. Returns error on Movie1Slice with no elements. See: http://clipperhouse.github.io/gen/#MinCustom
func (rcv Movie1Slice) MinDollars(fn func(Movie1) Dollars) (result Dollars, err error) {
	l := len(rcv)
	if l == 0 {
		err = errors.New("cannot determine Min of zero-length Movie1Slice")
		return
	}
	result = fn(rcv[0])
	if l > 1 {
		for _, v := range rcv[1:] {
			f := fn(v)
			if f < result {
				result = f
			}
		}
	}
	return
}
